version: '3'
services:
  etl-template:
    image: akboyd88/etl-template:latest
    ports:
      - "8080:8080"
      - "443:443"
      - "80:80"
    depends_on:
      - postgres
      - kafka
  postgres:
    image: "postgres"
    restart: always
    env_file:
      - ./env/prd/database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  influxdb:
    image: influxdb:latest
    restart: always
    env_file:
      - ./env/prd/influxdb.env
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ./service_configs/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./service_configs/influxdb/init:/docker-entrypoint-initdb.d
  kafka:
    image: confluentinc/cp-kafka:5.4.1
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LOG_DIRS=/logs
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2182
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29094,PLAINTEXT_HOST://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - kafka-logs:/logs
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    volumes:
      - zookeeper-data:/datalog
    restart: always
    ports:
      - "9182:2182"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2182
volumes:
  database-data:
  kafka-logs:
  zookeeper-data:
  influxdb-data: