version: '3'
services:
  etl-template:
    image: akboyd88/etl-template:latest
    labels:
      - "traefik.http.routers.etl-template.rule=Host(`etltemplate.docker.localhost`)"
    expose:
      - "80"
    depends_on:
      - postgres
      - kafka
  reverse-proxy:
    image: traefik:v2.4
    restart: always
    command: --configFile=/etc/traefik/traefik.toml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./service_configs/traefik/certs:/certs
      - ./service_configs/traefik/traefik.toml:/etc/traefik/traefik.toml
  postgres:
    image: "postgres"
    env_file:
      - ./env/prd/database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    expose:
      - "5432"
  kafka:
    image: confluentinc/cp-kafka:5.4.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2182
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29094,PLAINTEXT_HOST://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    expose:
      - "2182"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2182
volumes:
  database-data: